#management.endpoints.enabled-by-default=false
#management.endpoint.info.enabled=true
#management.endpoint.metrics.enabled=true
#management.endpoint.health.enabled=true
#management.endpoint.conditions.enabled=true
#management.endpoint.env.enabled=true
#management.endpoints.web.exposure.include=info,health,beans,conditions,metrics,env
#
##management.endpoints.web.base-path=/
#management.endpoints.web.path-mapping.health=healthcheck
#
#spring.security.user.name=admin
#spring.security.user.password=admin

#server.servlet.context-path=/foo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  aop:
    auto: true
    proxy-target-class: true
  banner:
    charset: UTF-8a

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, beans, env
